### ISSUE TITLE
Post notification toggle

### ISSUE THREAD

**Issue by sk22** [sk22/mastodon-android-fork#10]

**Comment by kescherCode** [comment]
This is probably re: the missing toggle here, right? No notifications for new posts by people one subscribed to?
![A screenshot of the app, where some notification settings are shown. The one missing are those for new posts by people you follow where you've subscribed to notifications.](https://user-images.githubusercontent.com/23276523/170845791-ebafc342-0d62-4634-a1c4-a2c3cf0cff8b.png)

**Comment by sk22** [comment]
> This is probably re: the missing toggle here, right? No notifications for new posts by people one subscribed to? ![A screenshot of the app, where some notification settings are shown. The one missing are those for new posts by people you follow where you've subscribed to notifications.](https://user-images.githubusercontent.com/23276523/170845791-ebafc342-0d62-4634-a1c4-a2c3cf0cff8b.png)

yep, looks right! a toggle here (along with a android notifs category) + a bell symbol on profile pages to toggle notification from accounts
