### ISSUE TITLE
Reblog and favorites indicator layout

### ISSUE THREAD

**Issue by juandarr** [sk22/mastodon-android-fork#34]
Hi, first of all, thank you very much for the fork. The new features are super appreciated. I was comparing the official android app vs fork recently, and found something wrong with the UI. Here  is a picture for comparison: official to the left, fork to the right. 

![post-mastodon](https://user-images.githubusercontent.com/749275/200958843-f9d53472-a451-4e80-92be-1d2c0165a9b0.png)

I noticed the change immediately since it took me away from the post's content. Font should be smaller size, item and property at the same level and since it is secondary information, should be smaller overall. Is it easy to fix it? I installed Android studio so I could help, but maybe it is easier for you since you are familiarized with the whole structure. Cheers

**Comment by sk22** [comment]
ah, yeah, this was changed upstream for some reason. not a big fan of it either and i planned to maybe revert it, see comment in your pull request (thanks!!)

**Comment by sk22** [comment]
sooo i think i'm really happy with this (based on the old design), what do you think? :D

![Screenshot_2022-11-11-01-23-23-270-edit_org joinmastodon android](https://user-images.githubusercontent.com/6217438/201233720-48a6fb16-12f0-4c0b-8805-386e44ebfcfe.jpg)
![Screenshot_2022-11-11-01-23-51-493-edit_org joinmastodon android](https://user-images.githubusercontent.com/6217438/201233724-8d9f6d11-a387-43d1-8f9e-38b6f08a83fd.jpg)

**Comment by juandarr** [comment]
Wow, looks pretty good! Much better and cleaner than the one I proposed. Keep up the great work, cheers buddy 🍻

**Comment by juandarr** [comment]
I installed the version with the new changes and at first glance it works as expected. Sometimes it loses the horizontal layout (for the indicators reblog, favorites and edit) and it is all messed up again: 

![Screenshot_20221110-231653_Mastodos](https://user-images.githubusercontent.com/749275/201262738-51506bc3-2d2d-4152-a5ac-003c72484bb2.png)

**Comment by sk22** [comment]
that's because it uses a view called `org.joinmastodon.android.ui.views.AutoOrientationLinearLayout`, so that's actually intentional. but i think it would look better if the buttons just wrapped around instead of changing orientation, so i guess i'll try to change that

**Comment by sk22** [comment]
turns out wrapping children isn't as easy as telling a LinearLayout to just do that... i could use a third party dependency (like google's flexbox implementation) but i always ran into dependency collisions, so i just set the reblogs and favs to always be in one line using a LinearLayout. not what i was going for, but it works as expected

**Comment by juandarr** [comment]
Yeah, you need to define constraints and rules to achieve what you want. I checked the latest version and have a new alternative that occupies less vertical space, here is a picture of both layouts for comparison (current one to the left, alternative to the right). I can do the PR if you want, otherwise, it is alright. Cheers
![PR-changeOfFooterLayout-alternative](https://user-images.githubusercontent.com/749275/201469366-e54d5b5f-1d23-4783-a945-967259260ea2.png)

**Comment by sk22** [comment]
tbh, i don't think saving that one line at the cost of a line break inside the button is worth it. i don't think it's that bad to have a larger extended footer sometimes; it's not like this is shown on all posts anyway. and honestly, i do actually find it somewhat handy to see posted/last edited dates directly below each other; it makes it easier to compare.
if the extra line bothers you a lot, we can still reopen the issue, but i wouldn't know how best to fix this
