### ISSUE TITLE
No notifications on Los 19.1

### ISSUE THREAD

**Issue by samuraikid0** [sk22/mastodon-android-fork#8]
Hi , I'm using a samsung s7 with lineage Os 19.1
The notifications don't show up ..

Can you fix it ? Guide me if you need logs
Thanks for the fork with the extras it's smooth

Cheers !

**Comment by sk22** [comment]
mhhh, weird, sorry to hear.. can you try if the issue also happens on the official app? if yes, it's probably better to create an issue there..

**Comment by samuraikid0** [comment]
Ye no notification, ill open an issue there

Thanks !
